time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes nonexistingaccount 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes koelner 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes remscheider 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes nuernberger 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes koelner 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes nuernberger 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes muenchner 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Oranienburg 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Mainz 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Kassel 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Koeln 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Dortmund 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Bremen 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Darmstadt 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Munich 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Hamburg 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Moers 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Ludwigshafen 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Wuppertal 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Windischletten 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Kalbach 
time java -cp target/carpool-app-1.0-SNAPSHOT-jar-with-dependencies.jar org.jonglaria.app.App bestroutes Lindau 
